# utils/hyde_generator.py
import yaml
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
from openai import OpenAI
import numpy as np

load_dotenv()


def load_config(config_path="config.yaml"):
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def get_llm_for_hyde(config):
    provider = config["llm"]["provider"]
    temperature = config["llm"]["temperature"]

    if provider == "openai":
        return ChatOpenAI(
            model=config["llm"]["model_openai"],
            temperature=temperature
        )
    elif provider == "gemini":
        return ChatGoogleGenerativeAI(
            model=config["llm"]["model_gemini"],
            temperature=temperature
        )
    else:
        raise ValueError("Unsupported provider. Use openai or gemini.")
    
#generate_hyde_answer function generates a hypothetical answer to the user query. 
# It uses the LLM specified in the config.yaml file to generate a short,
# factual-sounding hypothetical answer which is richer in context to help a retrieval system.
def generate_hyde_answer(query, config_path="config.yaml"):
    """
    Generates a hypothetical answer to the user query.
    This synthetic answer is NOT guaranteed to be factual.
    """
    config = load_config(config_path)
    llm = get_llm_for_hyde(config)

    hyde_prompt = [
        ("system", 
         "Generate a short, factual-sounding hypothetical answer to help a retrieval system. "
         "Do NOT say you are guessing; produce a confident, concise paragraph."),
        ("human", f"Question: {query}\n\nHypothetical Answer:")
    ]

    synthetic_answer = llm.invoke(hyde_prompt).content.strip()
    return synthetic_answer

#get_openai_embedding funtion is used to get the embedding of the synthetic answer generated by the
# generate_hyde_answer function. It uses the official OpenAI SDK to create embeddings for the given text.
# The default model used for embedding is "text-embedding-3-small", but it can be changed by passing 
# a different model name as an argument.
def get_openai_embedding(synthetic_answer, model="text-embedding-3-small"):
    """
    Embeds a single text using the official OpenAI SDK (required for HyDE).
    """
    client = OpenAI()
    response = client.embeddings.create(
        model=model,
        input=[synthetic_answer]
    )
    return np.array(response.data[0].embedding, dtype=np.float32)

def get_gemini_embedding(synthetic_answer, model="models/text-embedding-004"):
    """
    Embeds text using Gemini embeddings.
    """
    from langchain_google_genai import GoogleGenerativeAIEmbeddings
    emb = GoogleGenerativeAIEmbeddings(model=model)
    return np.array(emb.embed_query(synthetic_answer), dtype=np.float32)

def generate_hyde_embedding(query, config_path="config.yaml"):
    """
    Main HyDE function:
    1. Creates synthetic answer
    2. Converts it into embedding
    3. Returns embedding vector (np.array) based on the provider specified in config.yaml (OpenAI or Gemini).
    """
    config = load_config(config_path)
    provider = config["llm"]["provider"]

    synthetic_answer = generate_hyde_answer(query, config_path)
    print(f"Query: {query}")
    print("\n🧪 Synthetic HyDE Answer: ", synthetic_answer)

    if provider == "openai":
        embedding = get_openai_embedding(synthetic_answer)
    else:
        embedding = get_gemini_embedding(synthetic_answer)

    return embedding